openapi: 3.0.1
info:
  title: Loan Calculator Assigment API
  description: This is a Loan Calculator API which will have a finance related operations endpoints such as calculate loan, calculate interest etc.
  version: 1.0.0
tags:
  - name: finance
    description: The finance API this will have a finance related operations endpoints such as calculate loan, calculate interest etc.

paths:
  /finance/loan:
    get:
      tags:
        - finance
      operationId: ValuateLoan
      description:  This endpoint is used to calculate a loan by given loan request.
      parameters:
        - name: clientId
          in: query
          description: The client id of the customer who is requesting the loan we will use this to calculate the loan based on the customer information.
          required: false
          schema:
            type: string
            format: uuid
        - name: loanAmount
          in: query
          description: The loan amount requested by the customer.
          required: true
          schema:
            type: number
            format: decimal
        - name: loanPeriodInMonths
          in: query
          description: The loan period in months requested by the customer.
          required: true
          schema:
            type: integer    
            
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: number
                format: decimal


