/*
 * Loan Calculator Assigment API
 *
 * This is a Loan Calculator API which will have a finance related operations endpoints such as calculate loan, calculate interest etc.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using LoanCalculatorApi.Attributes;
using LoanCalculatorApi.Models;

namespace LoanCalculatorApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class FinanceApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>This endpoint is used to calculate a loan by given loan request.</remarks>
        /// <param name="loanRequest">The loan request object</param>
        /// <param name="cancellationToken">The cancellation token to cancel the operation.</param>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/page/data")]
        [ValidateModelState]
        [SwaggerOperation("ValuateLoan")]
        [SwaggerResponse(statusCode: 200, type: typeof(decimal), description: "successful operation")]
        public virtual async Task<IActionResult> ValuateLoan([FromQuery (Name = "loanRequest")][Required()]LoanRequest loanRequest, CancellationToken cancellationToken)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(decimal));
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<decimal>(exampleJson)
            : default(decimal);
            //TODO: Change the data returned
            return await Task.FromResult<IActionResult>(new ObjectResult(example));
        }
    }
}
